name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - master
      - main
      ## - docs
    paths:
      - "mkdocs.yml"
      - "docs/**"

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: pip install mkdocs mkdocs-material mkdocstrings-python

      ## - name: Build and Deploy
      ##   run: |
      ##     export PYTHONPATH=$PYTHONPATH:$(pwd)
      ##     mkdocs gh-deploy --force

      - name: Build documentation
        run: mkdocs build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
